### PR TITLE
Clean up compilation flags and build with -Werror

### PR DESCRIPTION
**Pull request by tari01**

### CODE REVIEW

**Review by sunweaver — APPROVED** [review]
Nice catch! ACK.

**Comment by sunweaver** [comment]
Withdrawing approval due to CI builds...

**Comment by tari01** [comment]
@sunweaver 

Do you have any idea what the heck this is?

https://app.travis-ci.com/github/AyatanaIndicators/ayatana-indicator-session/jobs/552670012

The other builds are fine...

**Review by sunweaver — APPROVED** [review]
LGTM

**Pull request merged**
