### PR TITLE
Fix deprecations and build warnings

### LINKED ISSUE #10: Fix g_type_class_add_private
Fix deprecated g_type_class_add_private and friends

### PR DESCRIPTION
**Pull request by tari01**
fixes #10

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01: there is another devPrivate code portion to be ported in the unit test code:

```
[ 62%] Building C object tests/CMakeFiles/backendmock.dir/backend-mock-guest.c.o
cd /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests && /usr/bin/cc -DINDICATOR_SERVICE_DIR=\"/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests\" -DSCHEMA_DIR=\"/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests\" -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/src -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/src -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests  -g -O2 -fdebug-prefix-map=/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2     -Wall -pedantic -Wextra -Wno-missing-field-initializers -g -o CMakeFiles/backendmock.dir/backend-mock-guest.c.o   -c /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-guest.c
/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-guest.c: In function ‘indicator_session_guest_mock_class_init’:
/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-guest.c:104:3: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
   g_type_class_add_private (klass, sizeof (IndicatorSessionGuestMockPriv));
   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-guest.h:24,
                 from /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-guest.c:22:
/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 void     g_type_class_add_private       (gpointer                    g_class,
          ^~~~~~~~~~~~~~~~~~~~~~~~
[ 63%] Building C object tests/CMakeFiles/backendmock.dir/backend-mock-users.c.o
cd /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests && /usr/bin/cc -DINDICATOR_SERVICE_DIR=\"/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests\" -DSCHEMA_DIR=\"/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests\" -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/src -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/src -I/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/obj-x86_64-linux-gnu/tests  -g -O2 -fdebug-prefix-map=/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2     -Wall -pedantic -Wextra -Wno-missing-field-initializers -g -o CMakeFiles/backendmock.dir/backend-mock-users.c.o   -c /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-users.c
/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-users.c: In function ‘indicator_session_users_mock_class_init’:
/home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-users.c:124:3: warning: ‘g_type_class_add_private’ is deprecated [-Wdeprecated-declarations]
   g_type_class_add_private (klass, sizeof (IndicatorSessionUsersMockPriv));
   ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/gobject/gobject.h:24,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock.h:23,
                 from /home/mike/MyDocuments/4projects/ayatana-upstream/ayatana-indicator-session.upstream/ayatana-indicator-session/tests/backend-mock-users.c:20:
/usr/include/glib-2.0/gobject/gtype.h:1303:10: note: declared here
 void     g_type_class_add_private       (gpointer                    g_class,
          ^~~~~~~~~~~~~~~~~~~~~~~~
[ 65%] Linking C static library libbackendmock.a
```

**Comment by sunweaver** [comment]
@tari01: I can merge this PR now and open an issue for the remaining bit or you add another commit to this PR's update branch. What do you prefer?

**Comment by tari01** [comment]
> @tari01: I can merge this PR now and open an issue for the remaining bit or you add another commit to this PR's update branch. What do you prefer?

Please do so. The Unit Tests are a different issue.

**Review by sunweaver — APPROVED** [review]
ok, then. LGTM, devPrivates code bit in unit test will be dealt with via a different PR.

**Pull request merged**
